---
title: "Analysis"
output: html_document
---

```{r, echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggplot2)
library(ggpubr)
library(knitr)
library(DescTools)
# install.packages("kableExtra")
library(kableExtra)
knitr::opts_knit$set(root.dir = "~/UOA-Nastaliq-Keyboard/DiscountEvaluation/src_r/")
```

```{r}
data1_unigram <- read.csv("../data/monad/dakshina_dataset.csv")
data1_bigram <- read.csv("../data/dyad/dakshina_dataset.csv")
data1_sentence <- read.csv("../data/sentence/score/dakshina_dataset.csv")
data1_levenshtine <- read.csv("../data/sentence/distance/dakshina_dataset.csv")

data2_unigram <- read.csv("../data/monad/roUrParl_dataset.csv")
data2_bigram <- read.csv("../data/dyad/roUrParl_dataset.csv")
data2_sentence <- read.csv("../data/sentence/score/roUrParl_dataset.csv")
data2_levenshtine <- read.csv("../data/sentence/distance/roUrParl_dataset.csv")
```

```{r, echo=FALSE}
# Calculating some additional stuff for help in analysis
combine_fingers <- function(df) {
  # Combined finger counts
  df$Press_Little <- df$Press_L_Little + df$Press_R_Little
  df$Press_Ring   <- df$Press_L_Ring   + df$Press_R_Ring
  df$Press_Middle <- df$Press_L_Middle + df$Press_R_Middle
  df$Press_Index  <- df$Press_L_Index  + df$Press_R_Index
  
  # Combined distance counts
  df$Dist_Little  <- df$Dist_L_Little + df$Dist_R_Little
  df$Dist_Ring    <- df$Dist_L_Ring   + df$Dist_R_Ring
  df$Dist_Middle  <- df$Dist_L_Middle + df$Dist_R_Middle
  df$Dist_Index   <- df$Dist_L_Index  + df$Dist_R_Index
  
  # Combined hand counts
  df$Press_L <- df$Press_L_Little + df$Press_L_Ring + df$Press_L_Middle + df$Press_L_Index
  df$Press_R <- df$Press_R_Little + df$Press_R_Ring + df$Press_R_Middle + df$Press_R_Index
  
  # Combined hand distance
  df$Dist_L <- df$Dist_L_Little + df$Dist_L_Ring + df$Dist_L_Middle + df$Dist_L_Index
  df$Dist_R <- df$Dist_R_Little + df$Dist_R_Ring + df$Dist_R_Middle + df$Dist_R_Index
  return(df)
}

data1_sentence<-combine_fingers(data1_sentence)
data2_sentence<-combine_fingers(data2_sentence)


data1_sentence_long <- data1_sentence %>%
  gather(key = "Finger", value = "Press", Press_L_Little, Press_L_Ring, Press_L_Middle, Press_L_Index, Press_R_Little, Press_R_Ring, Press_R_Middle, Press_R_Index) %>%
  convert_as_factor(ID, Finger)

data2_sentence_long <- data2_sentence %>%
  gather(key = "Finger", value = "Press", Press_L_Little, Press_L_Ring, Press_L_Middle, Press_L_Index, Press_R_Little, Press_R_Ring, Press_R_Middle, Press_R_Index) %>%
  convert_as_factor(ID, Finger)

data1_sentence_long_dist <- data1_sentence %>%
  gather(key = "Finger", value = "Dist", Dist_L_Little, Dist_L_Ring, Dist_L_Middle, Dist_L_Index, Dist_R_Little, Dist_R_Ring, Dist_R_Middle, Dist_R_Index) %>%
  convert_as_factor(ID, Finger)

data2_sentence_long_dist <- data2_sentence %>%
  gather(key = "Finger", value = "Dist", Dist_L_Little, Dist_L_Ring, Dist_L_Middle, Dist_L_Index, Dist_R_Little, Dist_R_Ring, Dist_R_Middle, Dist_R_Index) %>%
  convert_as_factor(ID, Finger)
```

## Key-press:
```{r, echo=FALSE}
# bar graphs showing per hand, per finger, per finger hand
```

```{r, echo=FALSE}
# Friedman tests
kruskals <- function(df) {
  sub <- subset(df, Keyboard == "CRULP")
  test1 <- kruskal_test(df, Press ~ Finger)
  effsize1 <- kruskal_effsize(df, Press ~ Finger)
  
  sub <- subset(df, Keyboard == "IME")
  test2 <- kruskal_test(df, Press ~ Finger)
  effsize2 <- kruskal_effsize(df, Press ~ Finger)
  
  sub <- subset(df, Keyboard == "WINDOWS")
  test3 <- kruskal_test(df, Press ~ Finger)
  effsize3 <- kruskal_effsize(df, Press ~ Finger)

  # Create a summary dataframe
  return (data.frame(
    Condition = c("CRULP", "IME", "WINDOWS"),
    statistic = c(test1$statistic, test2$statistic, test3$statistic),
    df = c(test1$df, test2$df, test3$df),
    p = c(test1$p, test2$p, test3$p),
    W  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize)
  ))
}

pairwise_comp <- function(df){
  sub <- subset(df, Keyboard == "CRULP")
  test1 <- wilcox_test(df,Press ~ Finger, p.adjust.method = "bonferroni")
  effsize1<-wilcox_effsize(df,Press ~ Finger, paired = TRUE)
  
  sub <- subset(df, Keyboard == "IME")
  test2 <- wilcox_test(df,Press ~ Finger, p.adjust.method = "bonferroni")
  effsize2<-wilcox_effsize(df,Press ~ Finger, paired = TRUE)
  
  sub <- subset(df, Keyboard == "WINDOWS")
  test3 <- wilcox_test(df,Press ~ Finger, p.adjust.method = "bonferroni")
  effsize3<-wilcox_effsize(df,Press ~ Finger, paired = TRUE)

  return (data.frame(
    Condition = c("CRULP", "IME", "WINDOWS"),
    group1 = c(test1$group1, test2$group1, test3$group1),
    group2 = c(test1$group2, test2$group2, test3$group2),
    n1 = c(test1$n1, test2$n1, test3$n1),
    n2 = c(test1$n2, test2$n2, test3$n2),
    statistic = c(test1$statistic, test2$statistic, test3$statistic),
    p = c(test1$p.adj, test2$p.adj, test3$p.adj),
    Z  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize)
  ))
}

kruskals(data1_sentence_long)
pairwise_comp(data1_sentence_long)

#kruskals(data2_sentence_long)
#pairwise_comp(data2_sentence_long)
```

```{r, echo=TRUE}
# Friedman tests
friedmans <- function(df) {
  test1 <- friedman_test(df, Press_L_Little ~ Keyboard | ID)
  effsize1 <- friedman_effsize(df, Press_L_Little ~ Keyboard | ID)
  
  test2 <- friedman_test(df, Press_R_Little ~ Keyboard | ID)
  effsize2 <- friedman_effsize(df, Press_R_Little ~ Keyboard | ID)
  
  test3 <- friedman_test(df, Press_L_Ring ~ Keyboard | ID)
  effsize3 <- friedman_effsize(df, Press_L_Ring ~ Keyboard | ID)
  
  test4 <- friedman_test(df, Press_R_Ring ~ Keyboard | ID)
  effsize4 <- friedman_effsize(df, Press_R_Ring ~ Keyboard | ID)
  
  test5 <- friedman_test(df, Press_L_Middle ~ Keyboard | ID)
  effsize5 <- friedman_effsize(df, Press_L_Middle ~ Keyboard | ID)
  
  test6 <- friedman_test(df, Press_R_Middle ~ Keyboard | ID)
  effsize6 <- friedman_effsize(df, Press_R_Middle ~ Keyboard | ID)
  
  test7 <- friedman_test(df, Press_L_Index ~ Keyboard | ID)
  effsize7 <- friedman_effsize(df, Press_L_Index ~ Keyboard | ID)
  
  test8 <- friedman_test(df, Press_R_Index ~ Keyboard | ID)
  effsize8 <- friedman_effsize(df, Press_R_Index ~ Keyboard | ID)
  
  test9 <- friedman_test(df, Press_L ~ Keyboard | ID)
  effsize9 <- friedman_effsize(df, Press_L ~ Keyboard | ID)
  
  test10 <- friedman_test(df, Press_R ~ Keyboard | ID)
  effsize10 <- friedman_effsize(df, Press_R ~ Keyboard | ID)
  
  # Create a summary dataframe
  return (data.frame(
    Condition = c("Press_L_Little", "Press_R_Little","Press_L_Ring", "Press_R_Ring","Press_L_Middle", "Press_R_Middle", "Press_L_Index","Press_R_Index", "Press_L", "Press_R"),
    statistic = c(test1$statistic, test2$statistic, test3$statistic, test4$statistic, test5$statistic, test6$statistic, test7$statistic, test8$statistic, test9$statistic, test10$statistic),
    df = c(test1$df, test2$df, test3$df, test4$df, test5$df, test6$df, test7$df, test8$df, test9$df, test10$df),
    p = c(test1$p, test2$p, test3$p, test4$p, test5$p, test6$p, test7$p, test8$p, test9$p ,test10$p),
    W  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize, effsize4$effsize, effsize5$effsize, effsize6$effsize, effsize7$effsize, effsize8$effsize, effsize9$effsize, effsize10$effsize)
  ))
}

pairwise_comp <- function(df){
  test1 <- wilcox_test(df,Press_L_Little ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize1<-wilcox_effsize(df,Press_L_Little ~ Keyboard, paired = TRUE)
  
  test2 <- wilcox_test(df,Press_R_Little ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize2<-wilcox_effsize(df,Press_R_Little ~ Keyboard, paired = TRUE)
  
  test3 <- wilcox_test(df,Press_L_Ring ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize3<-wilcox_effsize(df,Press_L_Ring ~ Keyboard, paired = TRUE)
  
  test4 <- wilcox_test(df,Press_R_Ring ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize4<-wilcox_effsize(df,Press_R_Ring ~ Keyboard, paired = TRUE)
  
  test5 <- wilcox_test(df,Press_L_Middle ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize5<-wilcox_effsize(df,Press_L_Middle ~ Keyboard, paired = TRUE)
  
  test6 <- wilcox_test(df,Press_R_Middle ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize6<-wilcox_effsize(df,Press_R_Middle ~ Keyboard, paired = TRUE)
  
  test7 <- wilcox_test(df,Press_L_Index ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize7<-wilcox_effsize(df,Press_L_Index ~ Keyboard, paired = TRUE)
  
  test8 <- wilcox_test(df,Press_R_Index ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize8<-wilcox_effsize(df,Press_R_Index ~ Keyboard, paired = TRUE)
  
  test9 <- wilcox_test(df,Press_L ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize9<-wilcox_effsize(df,Press_L ~ Keyboard, paired = TRUE)
  
  test10 <- wilcox_test(df,Press_R ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize10<-wilcox_effsize(df,Press_R ~ Keyboard, paired = TRUE)
  
  
  return (data.frame(
    Measuer = c("Press_L_Little", "Press_R_Little","Press_L_Ring", "Press_R_Ring","Press_L_Middle", "Press_R_Middle", "Press_L_Index","Press_R_Index", "Press_L", "Press_R"),
    group1 = c(test1$group1, test2$group1, test3$group1, test4$group1, test5$group1, test6$group1, test7$group1, test8$group1, test9$group1, test10$group1),
    group2 = c(test1$group2, test2$group2, test3$group2, test4$group2, test5$group2, test6$group2, test7$group2, test8$group2, test9$group2, test10$group2),
    n1 = c(test1$n1, test2$n1, test3$n1, test4$n1, test5$n1, test6$n1, test7$n1, test8$n1, test9$n1, test10$n1),
    n2 = c(test1$n2, test2$n2, test3$n2, test4$n2, test5$n2, test6$n2, test7$n2, test8$n2, test9$n2, test10$n2),
    statistic = c(test1$statistic, test2$statistic, test3$statistic, test4$statistic, test5$statistic, test6$statistic, test7$statistic, test8$statistic, test9$statistic, test10$statistic),
    p = c(test1$p.adj, test2$p.adj, test3$p.adj, test4$p.adj, test5$p.adj, test6$p.adj, test7$p.adj, test8$p.adj, test9$p.adj ,test10$p.adj),
    Z  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize, effsize4$effsize, effsize5$effsize, effsize6$effsize, effsize7$effsize, effsize8$effsize, effsize9$effsize, effsize10$effsize)
  ))
}
  
friedmans(data1_sentence)
pairwise_comp(data1_sentence)

#friedmans(data2_sentence)
#pairwise_comp(data2_sentence)
```

## Typing Distance:

```{r, echo=FALSE}
# Friedman tests
kruskals <- function(df) {
  sub <- subset(df, Keyboard == "CRULP")
  test1 <- kruskal_test(df, Dist ~ Finger)
  effsize1 <- kruskal_effsize(df, Dist ~ Finger)
  
  sub <- subset(df, Keyboard == "IME")
  test2 <- kruskal_test(df, Dist ~ Finger)
  effsize2 <- kruskal_effsize(df, Dist ~ Finger)
  
  sub <- subset(df, Keyboard == "WINDOWS")
  test3 <- kruskal_test(df, Dist ~ Finger)
  effsize3 <- kruskal_effsize(df, Dist ~ Finger)

  # Create a summary dataframe
  return (data.frame(
    Condition = c("CRULP", "IME", "WINDOWS"),
    statistic = c(test1$statistic, test2$statistic, test3$statistic),
    df = c(test1$df, test2$df, test3$df),
    p = c(test1$p, test2$p, test3$p),
    W  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize)
  ))
}

pairwise_comp <- function(df){
  sub <- subset(df, Keyboard == "CRULP")
  test1 <- wilcox_test(df,Dist ~ Finger, p.adjust.method = "bonferroni")
  effsize1<-wilcox_effsize(df,Dist ~ Finger, paired = TRUE)
  
  sub <- subset(df, Keyboard == "IME")
  test2 <- wilcox_test(df,Dist ~ Finger, p.adjust.method = "bonferroni")
  effsize2<-wilcox_effsize(df,Dist ~ Finger, paired = TRUE)
  
  sub <- subset(df, Keyboard == "WINDOWS")
  test3 <- wilcox_test(df,Dist ~ Finger, p.adjust.method = "bonferroni")
  effsize3<-wilcox_effsize(df,Dist ~ Finger, paired = TRUE)

  return (data.frame(
    Condition = c("CRULP", "IME", "WINDOWS"),
    group1 = c(test1$group1, test2$group1, test3$group1),
    group2 = c(test1$group2, test2$group2, test3$group2),
    n1 = c(test1$n1, test2$n1, test3$n1),
    n2 = c(test1$n2, test2$n2, test3$n2),
    statistic = c(test1$statistic, test2$statistic, test3$statistic),
    p = c(test1$p.adj, test2$p.adj, test3$p.adj),
    Z  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize)
  ))
}

kruskals(data1_sentence_long_dist)
pairwise_comp(data1_sentence_long_dist)

#kruskals(data2_sentence_long)
#pairwise_comp(data2_sentence_long)
```

```{r, echo=TRUE}
# Friedman tests
friedmans <- function(df) {
  test1 <- friedman_test(df, Dist_L_Little ~ Keyboard | ID)
  effsize1 <- friedman_effsize(df, Dist_L_Little ~ Keyboard | ID)
  
  test2 <- friedman_test(df, Dist_R_Little ~ Keyboard | ID)
  effsize2 <- friedman_effsize(df, Dist_R_Little ~ Keyboard | ID)
  
  test3 <- friedman_test(df, Dist_L_Ring ~ Keyboard | ID)
  effsize3 <- friedman_effsize(df, Dist_L_Ring ~ Keyboard | ID)
  
  test4 <- friedman_test(df, Dist_R_Ring ~ Keyboard | ID)
  effsize4 <- friedman_effsize(df, Dist_R_Ring ~ Keyboard | ID)
  
  test5 <- friedman_test(df, Dist_L_Middle ~ Keyboard | ID)
  effsize5 <- friedman_effsize(df, Dist_L_Middle ~ Keyboard | ID)
  
  test6 <- friedman_test(df, Dist_R_Middle ~ Keyboard | ID)
  effsize6 <- friedman_effsize(df, Dist_R_Middle ~ Keyboard | ID)
  
  test7 <- friedman_test(df, Dist_L_Index ~ Keyboard | ID)
  effsize7 <- friedman_effsize(df, Dist_L_Index ~ Keyboard | ID)
  
  test8 <- friedman_test(df, Dist_R_Index ~ Keyboard | ID)
  effsize8 <- friedman_effsize(df, Dist_R_Index ~ Keyboard | ID)
  
  test9 <- friedman_test(df, Dist_L ~ Keyboard | ID)
  effsize9 <- friedman_effsize(df, Dist_L ~ Keyboard | ID)
  
  test10 <- friedman_test(df, Dist_R ~ Keyboard | ID)
  effsize10 <- friedman_effsize(df, Dist_R ~ Keyboard | ID)
  
  # Create a summary dataframe
  return (data.frame(
    Condition = c("Dist_L_Little", "Dist_R_Little","Dist_L_Ring", "Dist_R_Ring","Dist_L_Middle", "Dist_R_Middle", "Dist_L_Index","Dist_R_Index", "Dist_L", "Dist_R"),
    statistic = c(test1$statistic, test2$statistic, test3$statistic, test4$statistic, test5$statistic, test6$statistic, test7$statistic, test8$statistic, test9$statistic, test10$statistic),
    df = c(test1$df, test2$df, test3$df, test4$df, test5$df, test6$df, test7$df, test8$df, test9$df, test10$df),
    p = c(test1$p, test2$p, test3$p, test4$p, test5$p, test6$p, test7$p, test8$p, test9$p ,test10$p),
    W  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize, effsize4$effsize, effsize5$effsize, effsize6$effsize, effsize7$effsize, effsize8$effsize, effsize9$effsize, effsize10$effsize)
  ))
}

pairwise_comp <- function(df){
  test1 <- wilcox_test(df,Dist_L_Little ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize1<-wilcox_effsize(df,Dist_L_Little ~ Keyboard, paired = TRUE)
  
  test2 <- wilcox_test(df,Dist_R_Little ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize2<-wilcox_effsize(df,Dist_R_Little ~ Keyboard, paired = TRUE)
  
  test3 <- wilcox_test(df,Dist_L_Ring ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize3<-wilcox_effsize(df,Dist_L_Ring ~ Keyboard, paired = TRUE)
  
  test4 <- wilcox_test(df,Dist_R_Ring ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize4<-wilcox_effsize(df,Dist_R_Ring ~ Keyboard, paired = TRUE)
  
  test5 <- wilcox_test(df,Dist_L_Middle ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize5<-wilcox_effsize(df,Dist_L_Middle ~ Keyboard, paired = TRUE)
  
  test6 <- wilcox_test(df,Dist_R_Middle ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize6<-wilcox_effsize(df,Dist_R_Middle ~ Keyboard, paired = TRUE)
  
  test7 <- wilcox_test(df,Dist_L_Index ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize7<-wilcox_effsize(df,Dist_L_Index ~ Keyboard, paired = TRUE)
  
  test8 <- wilcox_test(df,Dist_R_Index ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize8<-wilcox_effsize(df,Dist_R_Index ~ Keyboard, paired = TRUE)
  
  test9 <- wilcox_test(df,Dist_L ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize9<-wilcox_effsize(df,Dist_L ~ Keyboard, paired = TRUE)
  
  test10 <- wilcox_test(df,Dist_R ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
  effsize10<-wilcox_effsize(df,Dist_R ~ Keyboard, paired = TRUE)
  
  
  return (data.frame(
    Measuer = c("Dist_L_Little", "Dist_R_Little","Dist_L_Ring", "Dist_R_Ring","Dist_L_Middle", "Dist_R_Middle", "Dist_L_Index","Dist_R_Index", "Dist_L", "Dist_R"),
    group1 = c(test1$group1, test2$group1, test3$group1, test4$group1, test5$group1, test6$group1, test7$group1, test8$group1, test9$group1, test10$group1),
    group2 = c(test1$group2, test2$group2, test3$group2, test4$group2, test5$group2, test6$group2, test7$group2, test8$group2, test9$group2, test10$group2),
    n1 = c(test1$n1, test2$n1, test3$n1, test4$n1, test5$n1, test6$n1, test7$n1, test8$n1, test9$n1, test10$n1),
    n2 = c(test1$n2, test2$n2, test3$n2, test4$n2, test5$n2, test6$n2, test7$n2, test8$n2, test9$n2, test10$n2),
    statistic = c(test1$statistic, test2$statistic, test3$statistic, test4$statistic, test5$statistic, test6$statistic, test7$statistic, test8$statistic, test9$statistic, test10$statistic),
    p = c(test1$p.adj, test2$p.adj, test3$p.adj, test4$p.adj, test5$p.adj, test6$p.adj, test7$p.adj, test8$p.adj, test9$p.adj ,test10$p.adj),
    Z  = c(effsize1$effsize, effsize2$effsize, effsize3$effsize, effsize4$effsize, effsize5$effsize, effsize6$effsize, effsize7$effsize, effsize8$effsize, effsize9$effsize, effsize10$effsize)
  ))
}
  
friedmans(data1_sentence)
pairwise_comp(data1_sentence)

#friedmans(data2_sentence)
#pairwise_comp(data2_sentence)
```
## Stroke Evaluation:
