---
title: "Analysis_Simple"
output: html_document
---

## Simple Analysis

The first few code chunks are setup such as library importing, data reading and generation of a few additional features.

```{r, echo=FALSE}
library(tidyverse)
library(rstatix)
library(ggplot2)
library(ggpubr)
library(knitr)
# install.packages("kableExtra")
library(kableExtra)
knitr::opts_knit$set(root.dir = "~/UOA-Nastaliq-Keyboard/DiscountEvaluation/src_r/")
```

```{r}
data1_unigram <- read.csv("../data/monad/dakshina_dataset.csv")
data1_bigram <- read.csv("../data/dyad/dakshina_dataset.csv")
data1_sentence <- read.csv("../data/sentence/score/dakshina_dataset.csv")
data1_levenshtine <- read.csv("../data/sentence/distance/dakshina_dataset.csv")

data2_unigram <- read.csv("../data/monad/roUrParl_dataset.csv")
data2_bigram <- read.csv("../data/dyad/roUrParl_dataset.csv")
data2_sentence <- read.csv("../data/sentence/score/roUrParl_dataset.csv")
data2_levenshtine <- read.csv("../data/sentence/distance/roUrParl_dataset.csv")
```

```{r, echo=FALSE}
# Calculating some additional stuff for help in analysis
combine_fingers <- function(df) {
  # Combined finger press
  df$Press_Little <- df$Press_L_Little + df$Press_R_Little
  df$Press_Ring   <- df$Press_L_Ring   + df$Press_R_Ring
  df$Press_Middle <- df$Press_L_Middle + df$Press_R_Middle
  df$Press_Index  <- df$Press_L_Index  + df$Press_R_Index
  
  # Combined finger distance
  df$Dist_Little  <- df$Dist_L_Little + df$Dist_R_Little
  df$Dist_Ring    <- df$Dist_L_Ring   + df$Dist_R_Ring
  df$Dist_Middle  <- df$Dist_L_Middle + df$Dist_R_Middle
  df$Dist_Index   <- df$Dist_L_Index  + df$Dist_R_Index
  
  # Combined hand press
  df$Press_L <- df$Press_L_Little + df$Press_L_Ring + df$Press_L_Middle + df$Press_L_Index
  df$Press_R <- df$Press_R_Little + df$Press_R_Ring + df$Press_R_Middle + df$Press_R_Index
  
  # Combined hand distance
  df$Dist_L <- df$Dist_L_Little + df$Dist_L_Ring + df$Dist_L_Middle + df$Dist_L_Index
  df$Dist_R <- df$Dist_R_Little + df$Dist_R_Ring + df$Dist_R_Middle + df$Dist_R_Index
  
  # Total press
  df$Press <- df$Press_L + df$Press_R
  
  # Total distance
  df$Dist <- df$Dist_L + df$Dist_R
  return(df)
}

data1_bigram<-combine_fingers(data1_bigram)
data2_bigram<-combine_fingers(data2_bigram)

data1_sentence<-combine_fingers(data1_sentence)
data2_sentence<-combine_fingers(data2_sentence)

#data1_sentence_long_dist <- data1_sentence %>%
#  gather(key = "Finger", value = "Dist", Dist_L_Little, Dist_L_Ring, Dist_L_Middle, Dist_L_Index, Dist_R_Little, Dist_R_Ring, Dist_R_Middle, Dist_R_Index) %>%
#  convert_as_factor(ID, Finger)

#data2_sentence_long_dist <- data2_sentence %>%
#  gather(key = "Finger", value = "Dist", Dist_L_Little, Dist_L_Ring, Dist_L_Middle, Dist_L_Index, Dist_R_Little, Dist_R_Ring, Dist_R_Middle, Dist_R_Index) %>%
#  convert_as_factor(ID, Finger)
```

## Key Press Counts

------------------------------------------------------------------------

We can our analysis of key press counts with bar plots of the total key press counts for each keyboard. This will give us a general idea of how different they are.

```{r echo =" FALSE"}
ggplot(data1_sentence, aes(x=Keyboard, y=Press , fill=Keyboard )) + geom_bar(stat = "summary", fun = "sum")
```

Looking at the results we see that IME followed by CRULP then WINDOWS. This makes sense because the IME keyboard requires multiple keys to input characters that represent complicated sounds. For example خ has to be entered as "kh" on IME but requires only a single key on both WINDOWS and CRULP.

```{r, echo = FALSE}
data1_sentence %>%
  group_by(Keyboard) %>%
  get_summary_stats(Press, type = "common")
```

```{r, echo = FALSE}
ggviolin(data1_sentence, x = "Keyboard", y = "Press", fill = "Keyboard", add = "boxplot", add.params = list(fill = "white") ) + scale_y_log10() + labs (x= "Keyboard", y = "log10 scaled Key Press Count")
```

Looking at the descriptive violine we can see the data is quite skewed towards the left. There are also a number of outliers that contribute to the high variability observed. This is because the length of each sentence is not controlled so certain sentences have a really high key press count.The medians for key press counts is as expected with IME at the highest ( $median$ = 79, $IQR$ = 79), followed by CRULP ( $median$ = 71, $IQR$ = 70), then Windows ( $median$ = 70, $IQR$ = 70).

```{r, echo = FALSE}
test<-friedman_test(data1_sentence , Press ~ Keyboard | ID)
effsize<-friedman_effsize(data1_sentence , Press ~ Keyboard | ID)
result <- data.frame(
  statistic = c(test$statistic),
  df = c(test$df),
  p = c(test$p),
  W = c(effsize$effsize),
  magnitude = c(effsize$magnitude)
)
result
```

```{r, echo = FALSE}
test<-wilcox_test(data1_sentence, Press ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
effsize<-wilcox_effsize(data1_sentence,Press ~ Keyboard, paired = TRUE)
result <- data.frame(
  group1 = test$group1,
  group2 = test$group2,
  statistic = test$statistic,
  p = test$p.adj,
  R = effsize$effsize,
  magnitude = effsize$magnitude
)
result
```

Friedman’s test with `Press ~ Keyboard | Sentence` detected large difference ( $p$ \<0.001, $W$ = 0.6597) and pairwise comparison using Wilcox signed rank test with Bonferroni correction detected significant differences across all pairs. Given this we can say that IME indeed has the highest mean key press counts followed by CRULP then WINDOWS for all sentences in our data set.

### Key Press Distribution By Hand

```{r echo =" FALSE"}
data1_sentence_long <- data1_sentence %>%
  gather(key = "Hand", value = "Press", Press_L, Press_R) %>%
  convert_as_factor(ID, Hand)
```

```{r echo =" FALSE"}
ggplot(data1_sentence_long, aes(x=Keyboard, y=Press, fill=Hand)) + geom_bar(position = "dodge", stat = "summary", fun = "sum")+scale_fill_brewer(palette = "Set2")
```

```{r, echo = FALSE}
get_summary<-function(df,group,factor,value){
  sub_set <- subset(df, Keyboard == group)
  sub_set %>%
    group_by_at(factor) %>%
    get_summary_stats("Press", type = "common")
}

hand_summary<-function(df){
  summary1 <- get_summary(df,"CRULP", "Hand", "Press")
  summary2 <- get_summary(df,"IME", "Hand", "Press")
  summary3 <- get_summary(df,"WINDOWS", "Hand", "Press")
  return (
    bind_rows(
    summary1 %>% mutate(Keyboard = "CRULP"),
    summary2 %>% mutate(Keyboard = "IME"),
    summary3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_summary(data1_sentence_long)
```

```{r, echo = FALSE}
ggviolin(
  data1_sentence_long, x = "Keyboard", y = "Press", fill = "Hand", position = position_dodge(1)) +
  geom_boxplot(aes(x = Keyboard, y = Press, group = interaction(Keyboard, Hand)),fill = "white", width = 0.1, position = position_dodge(1)) +
  scale_y_log10() +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Keyboard", y = "Log10 Scaled Key Press Count")
```

```{r, echo=FALSE}
kruskals <- function(df, group, eq) {
  sub <- subset(df, Keyboard == group)
  test <- kruskal_test(sub, eq)
  effsize <- kruskal_effsize(sub,eq)
  
  return (data.frame(
    statistic = c(test$statistic),
    df = test$df,
    p = test$p,
    eta2 = effsize$effsize,
    magnitude = effsize$magnitude
  ))
}

hand_within<-function(df){
  test1 <- kruskals(data1_sentence_long, "CRULP", Press ~ Hand)
  test2 <- kruskals(data1_sentence_long, "IME",Press ~ Hand)
  test3 <- kruskals(data1_sentence_long, "WINDOWS",Press ~ Hand)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_within(data1_sentence_long)
```

```{r, echo=FALSE}
k_pairwise_comp <- function(df, group, eq) {
  sub <- subset(df, Keyboard == group)
  test <- wilcox_test(sub,eq, p.adjust.method = "bonferroni")
  effsize <- wilcox_effsize(sub, eq, paired = TRUE)
  
  return (data.frame(
    group1 = test$group1,
    group2 = test$group2,
    statistic = test$statistic,
    p = test$p,
    R = effsize$effsize,
    magnitude = effsize$magnitude
  ))
}

hand_within_pwc<-function(df){
  test1 <- k_pairwise_comp(df, "CRULP", Press ~ Hand)
  test2 <- k_pairwise_comp(df, "IME",Press ~ Hand)
  test3 <- k_pairwise_comp(df, "WINDOWS",Press ~ Hand)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_within_pwc(data1_sentence_long)
#Note: Approx 2 min with effect size
```

```{r, echo = FALSE}
friedmans <- function(df, eq) {
  test <- friedman_test(df, eq)
  effsize <- friedman_effsize(df,eq)
  
  return (data.frame(
    statistic = c(test$statistic),
    df = test$df,
    p = test$p,
    W = effsize$effsize,
    magnitude = effsize$magnitude
  ))
}

hand_btween<-function(df){
  test1 <- friedmans(df, Press_L ~ Keyboard|ID)
  test2 <- friedmans(df, Press_R ~ Keyboard|ID)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "L"),
    test2 %>% mutate(Hand = "R"))%>%
    select(Hand, everything()))
}

hand_btween(data1_sentence)
```

```{r, echo = FALSE}
f_pairwise_comp <- function(df, eq) {
  test <- wilcox_test(df,eq, p.adjust.method = "bonferroni")
  effsize <- wilcox_effsize(df,eq, paired = TRUE)
  
  return (data.frame(
    group1 = test$group1,
    group2 = test$group2,
    statistic = test$statistic,
    p = test$p,
    R = effsize$effsize,
    magnitude = effsize$magnitude
  ))
}

hand_between_pwc<-function(df){
  test1 <- f_pairwise_comp(df, Press_L ~ Keyboard)
  test2 <- f_pairwise_comp(df, Press_R ~ Keyboard)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "L"),
    test2 %>% mutate(Hand = "R"))%>%
    select(Hand, everything()))
}

hand_between_pwc(data1_sentence)
#Note: Approx 1 min with effect size
```

### Key Press Distribution By Finger

```{r echo =" FALSE"}
mapping <- c("L_Little" = "Little", "R_Little" = "Little",
             "L_Ring"   = "Ring",   "R_Ring"   = "Ring",
             "L_Middle" = "Middle", "R_Middle" = "Middle",
             "L_Index"  = "Index",  "R_Index"  = "Index")

data1_unigram$FingerCombined <- mapping[match(data1_unigram$Finger, names(mapping))]
data1_unigram$FingerCombined = factor(data1_unigram$FingerCombined, levels = c("Little", "Ring", "Middle","Index"), ordered = TRUE)

data2_unigram$FingerCombined <- mapping[match(data2_unigram$Finger, names(mapping))]
data2_unigram$FingerCombined = factor(data2_unigram$FingerCombined, levels = c("Little", "Ring", "Middle","Index"), ordered = TRUE)


data1_sentence_long <- data1_sentence %>%
  gather(key = "Finger", value = "Press", Press_Little, Press_Ring, Press_Middle, Press_Index) %>%
  convert_as_factor(ID, Finger)

data1_sentence_long$Finger <- factor(data1_sentence_long$Finger, levels = c("Press_Little", "Press_Ring", "Press_Middle", "Press_Index"))
```

```{r echo =" FALSE"}
ggplot(data1_sentence_long, aes(x=Keyboard, y=Press , fill=Finger )) + geom_bar(position = "dodge", stat = "summary", fun = "sum")+scale_fill_brewer(palette = "Set2")
```

```{r, echo = FALSE}
get_summary<-function(df,group,factor,value){
  sub_set <- subset(df, Keyboard == group)
  sub_set %>%
    group_by_at(factor) %>%
    get_summary_stats("Press", type = "common")
}

finger_summary<-function(df){
  summary1 <- get_summary(df,"CRULP", "Finger", "Press")
  summary2 <- get_summary(df,"IME", "Finger", "Press")
  summary3 <- get_summary(df,"WINDOWS", "Finger", "Press")
  return (
    bind_rows(
    summary1 %>% mutate(Keyboard = "CRULP"),
    summary2 %>% mutate(Keyboard = "IME"),
    summary3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_summary(data1_sentence_long)
```

```{r, echo = FALSE}
ggviolin(
  data1_sentence_long, x = "Keyboard", y = "Press", fill = "Finger", position = position_dodge(1)) +
  geom_boxplot(aes(x = Keyboard, y = Press, group = interaction(Keyboard, Finger)),fill = "white", width = 0.1, position = position_dodge(1)) +
  scale_y_log10() +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Keyboard", y = "Log10 Scaled Key Press Count")
```

```{r, echo=FALSE}
finger_within<-function(df){
  test1 <- kruskals(data1_sentence_long, "CRULP", Press ~ Finger)
  test2 <- kruskals(data1_sentence_long, "IME",Press ~ Finger)
  test3 <- kruskals(data1_sentence_long, "WINDOWS",Press ~ Finger)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_within(data1_sentence_long)
```

```{r, echo=FALSE}
finger_within_pwc<-function(df){
  test1 <- k_pairwise_comp(df, "CRULP", Press ~ Finger)
  test2 <- k_pairwise_comp(df, "IME",Press ~ Finger)
  test3 <- k_pairwise_comp(df, "WINDOWS",Press ~ Finger)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_within_pwc(data1_sentence_long)
#Note: Approx 4 min with effect size
```

```{r, echo = FALSE}
finger_btween<-function(df){
  test1 <- friedmans(df, Press_Little ~ Keyboard|ID)
  test2 <- friedmans(df, Press_Ring ~ Keyboard|ID)
  test3 <- friedmans(df, Press_Middle ~ Keyboard|ID)
  test4 <- friedmans(df, Press_Index ~ Keyboard|ID)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "Little"),
    test2 %>% mutate(Hand = "Ring"),
    test3 %>% mutate(Hand = "Middle"),
    test4 %>% mutate(Hand = "Index"))%>%
    select(Hand, everything()))
}

finger_btween(data1_sentence)
```

```{r, echo = FALSE}
finger_between_pwc<-function(df){
  test1 <- f_pairwise_comp(df, Press_Little ~ Keyboard)
  test2 <- f_pairwise_comp(df, Press_Ring ~ Keyboard)
  test3 <- f_pairwise_comp(df, Press_Middle ~ Keyboard)
  test4 <- f_pairwise_comp(df, Press_Index ~ Keyboard)
  return (
    bind_rows(
    test1 %>% mutate(Finger = "Little"),
    test2 %>% mutate(Finger = "Ring"),
    test3 %>% mutate(Finger = "Middle"),
    test4 %>% mutate(Finger = "Index"))%>%
    select(Finger, everything()))
}

finger_between_pwc(data1_sentence)
#Note: Approx 3 min with effect size
```

## Typing Distance

------------------------------------------------------------------------

```{r echo =" FALSE"}
ggplot(data1_sentence, aes(x=Keyboard, y=Dist , fill=Keyboard )) + geom_bar(stat = "summary", fun = "sum")
```

```{r, echo = FALSE}
data1_sentence %>%
  group_by(Keyboard) %>%
  get_summary_stats(Dist, type = "common")
```

```{r, echo = FALSE}
ggviolin(data1_sentence, x = "Keyboard", y = "Dist", fill = "Keyboard", add = "boxplot", add.params = list(fill = "white") ) + scale_y_log10() + labs (x= "Keyboard", y = "log10 scaled Key Press Count")
```

```{r, echo = FALSE}
test<-friedman_test(data1_sentence , Dist ~ Keyboard | ID)
effsize<-friedman_effsize(data1_sentence , Dist ~ Keyboard | ID)
result <- data.frame(
  statistic = c(test$statistic),
  df = c(test$df),
  p = c(test$p),
  W = c(effsize$effsize),
  magnitude = c(effsize$magnitude)
)
result
```

```{r, echo = FALSE}
test<-wilcox_test(data1_sentence, Dist ~ Keyboard, paired = TRUE, p.adjust.method = "bonferroni")
effsize<-wilcox_effsize(data1_sentence,Dist ~ Keyboard, paired = TRUE)
result <- data.frame(
  group1 = test$group1,
  group2 = test$group2,
  statistic = test$statistic,
  p = test$p.adj,
  R = effsize$effsize,
  magnitude = effsize$magnitude
)
result
```

### Key Press Distribution By Hand

```{r echo =" FALSE"}
data1_sentence_long <- data1_sentence %>%
  gather(key = "Hand", value = "Dist", Dist_L, Dist_R) %>%
  convert_as_factor(ID, Hand)
```

```{r echo =" FALSE"}
ggplot(data1_sentence_long, aes(x=Keyboard, y=Dist, fill=Hand)) + geom_bar(position = "dodge", stat = "summary", fun = "sum")+scale_fill_brewer(palette = "Set2")
```

```{r, echo = FALSE}
get_summary<-function(df,group,factor,value){
  sub_set <- subset(df, Keyboard == group)
  sub_set %>%
    group_by_at(factor) %>%
    get_summary_stats("Press", type = "common")
}

hand_summary<-function(df){
  summary1 <- get_summary(df,"CRULP", "Hand", "Dist")
  summary2 <- get_summary(df,"IME", "Hand", "Dist")
  summary3 <- get_summary(df,"WINDOWS", "Hand", "Dist")
  return (
    bind_rows(
    summary1 %>% mutate(Keyboard = "CRULP"),
    summary2 %>% mutate(Keyboard = "IME"),
    summary3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_summary(data1_sentence_long)
```

```{r, echo = FALSE}
ggviolin(
  data1_sentence_long, x = "Keyboard", y = "Dist", fill = "Hand", position = position_dodge(1)) +
  geom_boxplot(aes(x = Keyboard, y = Dist, group = interaction(Keyboard, Hand)),fill = "white", width = 0.1, position = position_dodge(1)) +
  scale_y_log10() +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Keyboard", y = "Log10 Scaled Key Dist Count")
```

```{r, echo=FALSE}
hand_within<-function(df){
  test1 <- kruskals(data1_sentence_long, "CRULP", Dist ~ Hand)
  test2 <- kruskals(data1_sentence_long, "IME",Dist ~ Hand)
  test3 <- kruskals(data1_sentence_long, "WINDOWS",Dist ~ Hand)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_within(data1_sentence_long)
```

```{r, echo=FALSE}
hand_within_pwc<-function(df){
  test1 <- k_pairwise_comp(df, "CRULP", Dist ~ Hand)
  test2 <- k_pairwise_comp(df, "IME",Dist ~ Hand)
  test3 <- k_pairwise_comp(df, "WINDOWS",Dist ~ Hand)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

hand_within_pwc(data1_sentence_long)
#Note: Approx 2 min with effect size
```

```{r, echo = FALSE}
hand_btween<-function(df){
  test1 <- friedmans(df, Dist_L ~ Keyboard|ID)
  test2 <- friedmans(df, Dist_R ~ Keyboard|ID)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "L"),
    test2 %>% mutate(Hand = "R"))%>%
    select(Hand, everything()))
}

hand_btween(data1_sentence)
```

```{r, echo = FALSE}
hand_between_pwc<-function(df){
  test1 <- f_pairwise_comp(df, Dist_L ~ Keyboard)
  test2 <- f_pairwise_comp(df, Dist_R ~ Keyboard)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "L"),
    test2 %>% mutate(Hand = "R"))%>%
    select(Hand, everything()))
}

hand_between_pwc(data1_sentence)
#Note: Approx 1 min with effect size
```

### Key Press Distribution By Finger

```{r echo =" FALSE"}
data1_sentence_long <- data1_sentence %>%
  gather(key = "Finger", value = "Dist", Dist_Little, Dist_Ring, Dist_Middle, Dist_Index) %>%
  convert_as_factor(ID, Finger)

data1_sentence_long$Finger <- factor(data1_sentence_long$Finger, levels = c("Dist_Little", "Dist_Ring", "Dist_Middle", "Dist_Index"))
```

```{r echo =" FALSE"}
ggplot(data1_sentence_long, aes(x=Keyboard, y=Dist , fill=Finger )) + geom_bar(position = "dodge", stat = "summary", fun = "sum")+scale_fill_brewer(palette = "Set2")
```

```{r, echo = FALSE}
get_summary<-function(df,group,factor,value){
  sub_set <- subset(df, Keyboard == group)
  sub_set %>%
    group_by_at(factor) %>%
    get_summary_stats("Dist", type = "common")
}

finger_summary<-function(df){
  summary1 <- get_summary(df,"CRULP", "Finger", "Press")
  summary2 <- get_summary(df,"IME", "Finger", "Press")
  summary3 <- get_summary(df,"WINDOWS", "Finger", "Press")
  return (
    bind_rows(
    summary1 %>% mutate(Keyboard = "CRULP"),
    summary2 %>% mutate(Keyboard = "IME"),
    summary3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_summary(data1_sentence_long)
```

```{r, echo = FALSE}
ggviolin(
  data1_sentence_long, x = "Keyboard", y = "Dist", fill = "Finger", position = position_dodge(1)) +
  geom_boxplot(aes(x = Keyboard, y = Dist, group = interaction(Keyboard, Finger)),fill = "white", width = 0.1, position = position_dodge(1)) +
  scale_y_log10() +
  scale_fill_brewer(palette = "Set2") +
  labs(x = "Keyboard", y = "Log10 Scaled Key Dist Count")
```

```{r, echo=FALSE}
finger_within<-function(df){
  test1 <- kruskals(data1_sentence_long, "CRULP", Dist ~ Finger)
  test2 <- kruskals(data1_sentence_long, "IME",Dist ~ Finger)
  test3 <- kruskals(data1_sentence_long, "WINDOWS",Dist ~ Finger)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_within(data1_sentence_long)
```

```{r, echo=FALSE}
finger_within_pwc<-function(df){
  test1 <- k_pairwise_comp(df, "CRULP", Dist ~ Finger)
  test2 <- k_pairwise_comp(df, "IME",Dist ~ Finger)
  test3 <- k_pairwise_comp(df, "WINDOWS",Dist ~ Finger)
  return (
    bind_rows(
    test1 %>% mutate(Keyboard = "CRULP"),
    test2 %>% mutate(Keyboard = "IME"),
    test3 %>% mutate(Keyboard = "WINDOWS"))%>%
    select(Keyboard, everything()))
}

finger_within_pwc(data1_sentence_long)
#Note: Approx 4 min with effect size
```

```{r, echo = FALSE}
finger_btween<-function(df){
  test1 <- friedmans(df, Dist_Little ~ Keyboard|ID)
  test2 <- friedmans(df, Dist_Ring ~ Keyboard|ID)
  test3 <- friedmans(df, Dist_Middle ~ Keyboard|ID)
  test4 <- friedmans(df, Dist_Index ~ Keyboard|ID)
  return (
    bind_rows(
    test1 %>% mutate(Hand = "Little"),
    test2 %>% mutate(Hand = "Ring"),
    test3 %>% mutate(Hand = "Middle"),
    test4 %>% mutate(Hand = "Index"))%>%
    select(Hand, everything()))
}

finger_btween(data1_sentence)
```

```{r, echo = FALSE}
finger_between_pwc<-function(df){
  test1 <- f_pairwise_comp(df, Dist_Little ~ Keyboard)
  test2 <- f_pairwise_comp(df, Dist_Ring ~ Keyboard)
  test3 <- f_pairwise_comp(df, Dist_Middle ~ Keyboard)
  test4 <- f_pairwise_comp(df, Dist_Index ~ Keyboard)
  return (
    bind_rows(
    test1 %>% mutate(Finger = "Little"),
    test2 %>% mutate(Finger = "Ring"),
    test3 %>% mutate(Finger = "Middle"),
    test4 %>% mutate(Finger = "Index"))%>%
    select(Finger, everything()))
}

finger_between_pwc(data1_sentence)
#Note: Approx 3 min with effect size
```

## Stroke Analysis

------------------------------------------------------------------------

### Same Hand

### Same Finger

### Same Key

### Reach

### Hurdle
