###
//test root
POST http://localhost:8000/start_session

###
//test user creation
POST http://localhost:8000/user/
Content-Type: application/json

{
    "name": "Albert",
    "email": "alberta@ualberta.ca"
}

###
//test post of experimental results