###
//test root
POST http://yalmazabdullah.com/api//start_session

###
//test user creation
POST http://yalmazabdullah.com/api//user/
Content-Type: application/json

{
    "name": "Albert",
    "email": "alberta@ualberta.ca"
}

###
//test post of experimental results