version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend